# Generated by Django 2.2.3 on 2019-09-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='Cliente',
        ),
    ]
